workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: 3.24.0
      xcode: 15.4
      cocoapods: default
      groups:
        - ios-signing   # UI’de tanımladığın grup
    scripts:
      - name: Clean & pub get
        script: |
          set -e
          set -x
          flutter clean
          flutter pub get
      - name: Reinstall CocoaPods
        script: |
          set -e
          set -x
          cd ios
          rm -rf Pods Podfile.lock .symlinks Flutter/Flutter.framework Flutter/Flutter.podspec
          pod install --repo-update
          cd ..
      - name: Build IPA
        script: |
          set -e
          set -x
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      ios:
        app_store_connect:
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
          api_key: $APP_STORE_CONNECT_API_KEY
        ios_signing:
          distribution_type: app_store
          bundle_identifier: "com.sosyalguvenlik.mobil"
