import 'makale.dart';

final List<Makale> calisanMakaleler = [
  Makale(
    title: "İşsizlik Ödeneği Uygulaması ve Başvuru Şartları",
    content:
    "1. Yasal Dayanak\n"
        "İşsizlik ödeneği, 4447 sayılı İşsizlik Sigortası Kanunu kapsamında, sigortalı işsizlerin işsiz kaldıkları dönemde belirli şartlarla ekonomik destek almasını sağlayan bir sosyal güvenlik uygulamasıdır. Ödeneğin yürütülmesi Türkiye İş Kurumu (İŞKUR) tarafından sağlanır.\n"
        "2. İşsizlik Ödeneğine Hak Kazanma Şartları\n"
        "İşsizlik ödeneğinden yararlanmak için işçinin aşağıdaki koşulları sağlaması gerekir:\n"
        "• Kendi istek ve kusuru dışında işsiz kalmak,\n"
        "• Hizmet akdinin sona ermesinden önceki son 120 gün kesintisiz hizmet akdiyle çalışmış olmak,\n"
        "• Son üç yıl içinde en az 600 gün işsizlik sigortası primi ödemiş olmak,\n"
        "• İş sözleşmesinin sona ermesini takip eden 30 gün içinde İŞKUR’a şahsen ya da e-Devlet üzerinden başvuru yapmak.\n"
        "3. Ödeneğin Süresi ve Miktarı\n"
        "İşsizlik ödeneği, sigortalının prim ödeme süresine bağlı olarak aşağıdaki sürelerde verilir:\n"
        "• 600 gün prim ödeyenlere: 180 gün,\n"
        "• 900 gün prim ödeyenlere: 240 gün,\n"
        "• 1080 gün prim ödeyenlere: 300 gün.\n"
        "Ödeneğin günlük tutarı, sigortalının son dört aylık prime esas kazançları dikkate alınarak hesaplanır. Günlük işsizlik ödeneği, bu kazancın yüzde 40’ı oranındadır. Ancak, bu tutar brüt asgari ücretin yüzde 80’ini aşamaz. Ödenekten yalnızca damga vergisi kesilir, gelir ve sosyal güvenlik primi kesintisi yapılmaz.\n"
        "İşsizlik ödeneğine ilişkin hesaplamalar, Sosyal Güvenlik Mobil uygulamamız üzerinden pratik bir şekilde yapılabilmektedir.\n"
        "4. Başvuru Süreci\n"
        "Başvurular, iş sözleşmesinin sona erdiği tarihten itibaren 30 gün içinde yapılmalıdır. Başvuru kanalları şunlardır:\n"
        "• İŞKUR il ve ilçe müdürlüklerine şahsen başvuru,\n"
        "• e-Devlet kapısı üzerinden online başvuru.\n"
        "Başvuru sonrasında İŞKUR tarafından uygunluk değerlendirmesi yapılır ve işsizlik ödeneği almaya hak kazanan kişilere ödemeler PTT aracılığıyla veya belirtilen banka hesaplarına yapılır.\n"
        "5. İşsizlik Ödeneği Alanların Yükümlülükleri\n"
        "İşsizlik ödeneği süresince işsiz kişilerin şu yükümlülükleri bulunur:\n"
        "• İŞKUR tarafından önerilen iş ve meslek edindirme programlarına katılmak,\n"
        "• İş görüşmelerine zamanında gitmek,\n"
        "• Her ay belirli periyotlarla iş arama durumunu bildirmek.\n"
        "Bu yükümlülüklere uymayanların ödenekleri kesilebilir. Ayrıca, sigortalının işe başlaması durumunda da ödenek kesilir.\n"
        "6. Sonuç\n"
        "İşsizlik ödeneği, işten kendi isteği dışında ayrılan sigortalı çalışanlara geçici bir güvence sağlar. Bu ödenekten yararlanabilmek için hem sigortalılık süresi hem de başvuru zamanlaması büyük önem taşır. Çalışanların hak kaybı yaşamamaları adına işsizlik sigortası koşullarını önceden bilmeleri ve işten ayrıldıklarında zamanında başvuru yapmaları gereklidir.",
    emoji: "💸",
  ),
  Makale(
    title: "Kıdem Tazminatı Uygulaması ve Güncel Düzenlemeler",
    content:
    "1. Yasal Dayanak\n"
        "Kıdem tazminatı, işçilerin hizmet süresi boyunca edindikleri hakların korunmasını amaçlayan önemli bir iş hukuku kurumudur. Bu uygulama, 4857 sayılı İş Kanunu’nun ilgili hükümleriyle birlikte halen yürürlükte bulunan 1475 sayılı İş Kanunu’nun 14. maddesine dayanılarak yürütülmektedir. Bu maddede kıdem tazminatına hak kazanma ve ödeme koşulları detaylı olarak düzenlenmiştir.\n"
        "2. Hak Kazanma Şartları\n"
        "İşçinin kıdem tazminatına hak kazanabilmesi için bazı temel şartların sağlanması gerekir:\n"
        "• En az bir yıl süreyle çalışma: İşçi, aynı işveren nezdinde en az bir yıl süreyle çalışmış olmalıdır.\n"
        "• Belirli fesih nedenleri: Kıdem tazminatına hak kazandıran başlıca durumlar şunlardır:\n"
        "• İşverenin, iş sözleşmesini haklı bir neden olmaksızın feshetmesi,\n"
        "• İşçinin, haklı nedenle sözleşmeyi sona erdirmesi,\n"
        "• Emeklilik, yaşlılık veya malullük aylığına hak kazanılması,\n"
        "• Kadın işçinin evlilik nedeniyle, evlendiği tarihten itibaren bir yıl içinde işten ayrılması,\n"
        "• Erkek işçinin askerlik hizmeti nedeniyle ayrılması,\n"
        "• İşçinin vefat etmesi.\n"
        "Genel kural olarak işçinin kendi isteğiyle işten ayrılması kıdem tazminatı hakkı doğurmaz; ancak yukarıda belirtilen özel durumlar bu kuralın istisnasını oluşturur.\n"
        "3. Tazminatın Hesaplanması\n"
        "Kıdem tazminatı, işçinin çalıştığı her tam yıl için son brüt 30 günlük ücret esas alınarak hesaplanır. Bir yıldan artan süreler orantılı şekilde dikkate alınır. Hesaplamada şunlar dikkate alınır:\n"
        "• Brüt ücret: İşçinin son brüt maaşı esas alınır.\n"
        "• Sürekli ödemeler: Yemek, yol, konut yardımı gibi süreklilik arz eden ödemeler tazminata dahil edilir.\n"
        "• Vergilendirme: Kıdem tazminatından yalnızca damga vergisi kesilir. Bu vergi, brüt tazminat tutarının binde 7,59’u oranındadır. Gelir vergisinden ise muaf tutulur.\n"
        "4. Dijital Hesaplama Kolaylığı\n"
        "Kıdem tazminatı hesaplamaları, Sosyal Güvenlik Mobil uygulamamız üzerinden kolaylıkla yapılabilmektedir. Bu sayede çalışanlar, tahmini tazminat tutarlarını hızlıca öğrenebilirler.\n"
        "5. 2025 Yılı Tavan Tutarı\n"
        "Hazine ve Maliye Bakanlığı tarafından belirlenen kıdem tazminatı tavanı, 2025 yılı için 46.655,43 TL olarak açıklanmıştır. Bu tutar, işçinin maaşı ne kadar yüksek olursa olsun, her bir hizmet yılı için ödenecek azami kıdem tazminatını ifade eder. İşveren isterse bu sınırın üzerinde ödeme yapabilir; ancak fazladan ödenen kısım gelir vergisine tabi olur.\n"
        "6. Zamanaşımı Süresi\n"
        "Kıdem tazminatına ilişkin dava açma süresi, iş sözleşmesinin sona ermesinden itibaren beş yıldır. Bu sürenin geçirilmesi hâlinde yasal yollara başvurma hakkı ortadan kalkar.\n"
        "7. Sonuç\n"
        "Kıdem tazminatı, işçinin çalışma süresine dayalı sosyal güvencelerinin başında gelir. Bu nedenle fesih nedenlerinin doğru değerlendirilmesi, hesaplamaların usulüne uygun yapılması ve yasal sürelere riayet edilmesi, hem işçi hem de işveren açısından hak ve yükümlülüklerin sağlıklı yürütülmesi açısından kritik önem taşır.",
    emoji: "💼",
  ),
  Makale(
    title: "Yıllık Ücretli İzin Hakkı",
    content:
    "1. Yasal Dayanak ve Temel İlkeler\n"
        "Yıllık ücretli izin, çalışanların dinlenme hakkını korumaya yönelik anayasal ve yasal bir haktır. Türkiye’de bu hak, 4857 sayılı İş Kanunu’nun 53 ila 61. maddeleri ile Yıllık Ücretli İzin Yönetmeliği kapsamında düzenlenir. Bu düzenlemeler, işçinin dinlenmesini sağlayarak verimliliğini artırmayı ve sağlığını korumayı amaçlar.\n"
        "2. İzne Hak Kazanma Şartları\n"
        "Bir işçinin yıllık ücretli izne hak kazanabilmesi için aynı işverene bağlı olarak en az bir yıl çalışmış olması gerekir. Bu süreye deneme süresi de dahildir. İşçinin aynı işverene ait farklı işyerlerinde geçen hizmet süreleri birleştirilir. Ancak bir yıldan az süren mevsimlik işler bu hakkın dışında tutulur.\n"
        "3. İzin Süreleri\n"
        "İşçinin kıdemine göre yıllık izin süreleri aşağıdaki gibi belirlenmiştir:\n"
        "• 1 - 5 yıl arası (5 yıl dahil): En az 14 gün\n"
        "• 5 - 15 yıl arası: En az 20 gün\n"
        "• 15 yıl ve üzeri: En az 26 gün\n"
        "18 yaş altı ve 50 yaş üstü işçilere verilecek izin süresi en az 20 gündür. Yer altı işlerinde çalışanlara bu sürelerin üzerine 4 gün eklenir. Bu süreler, artırılabilir ancak azaltılamaz.\n"
        "4. İzin Kullanımı ve Bölünebilirlik\n"
        "Yıllık izin süreleri, kural olarak tek parça hâlinde kullanılmalıdır. Ancak işçi ve işverenin karşılıklı anlaşması durumunda, bir bölümü en az 10 gün olacak şekilde bölünebilir. Kaç parçaya bölünebileceği konusunda yasal bir sınır yoktur. İzin tarihi, işçinin talebi ve işin gereği gözetilerek işveren tarafından belirlenir.\n"
        "5. İzin Süresine Dahil Edilmeyen Günler\n"
        "Yıllık ücretli izin süresine rastlayan ulusal bayram, genel tatil ve hafta tatili günleri izin süresinden sayılmaz. Örneğin 14 günlük bir izne denk gelen 2 hafta sonu ve 1 resmi tatil varsa, işçi fiilen 17 gün izin kullanır. Bu düzenleme, işçinin tatil hakkını tam anlamıyla kullanmasını sağlamak amacı taşır.\n"
        "6. Yol İzni\n"
        "İşyerinin bulunduğu şehir dışında izin kullanacak işçilere, talep etmeleri ve belgelemeleri hâlinde işveren toplamda 4 güne kadar ücretsiz yol izni vermekle yükümlüdür. Bu süre, yıllık izne eklenmez ve işçinin yolculuk süresine destek amaçlıdır.\n"
        "7. İzin Ücreti ve Kullanılmayan Haklar\n"
        "İşçiye, yıllık izne çıkarken izin süresine ait ücreti eksiksiz ödenmelidir. İşçi, izin sırasında başka bir işte çalışamaz; aksi tespit edilirse, işveren ödediği izin ücretini geri talep edebilir. İş sözleşmesi feshedilen işçinin kullanmadığı yıllık izinleri varsa, bu günlerin ücreti kendisine ödenir. Bu alacaklar için 5 yıllık zamanaşımı süresi vardır.\n"
        "8. Kayıt Zorunluluğu\n"
        "İşverenler, çalışanların izin haklarını ve kullanım tarihlerini gösteren izin kayıt belgelerini tutmak zorundadır. Bu kayıtlar, hem işçi haklarının korunması hem de olası anlaşmazlıkların önlenmesi açısından önemlidir.\n"
        "9. Sonuç\n"
        "Yıllık ücretli izin, çalışanların dinlenerek verimliliklerini artırmalarına olanak tanıyan vazgeçilmez bir haktır. İşverenler, bu hakkı sağlamakla yükümlüdür; işçiler ise yasal haklarını zamanında ve bilinçli şekilde kullanmalıdır. Yıllık izin, yalnızca bir dinlenme arası değil, sağlıklı ve sürdürülebilir bir çalışma yaşamının temel dayanaklarından biridir.",
    emoji: "🏖️",
  ),
  Makale(
    title: "İş Güvenliği ve Çalışan Hakları",
    content:
    "1. Tanım ve Hukuki Dayanak\n"
        "İş güvenliği, çalışanların sağlığını korumak, iş kazalarını ve meslek hastalıklarını önlemek amacıyla alınan önlemler bütünüdür. Türkiye’de iş güvenliği, 6331 sayılı İş Sağlığı ve Güvenliği Kanunu ile düzenlenmiştir. Bu kanun, tüm çalışanlara eşit biçimde uygulanır ve hem kamu hem özel sektör işyerlerini kapsar. Ayrıca 4857 sayılı İş Kanunu, işverenin çalışanların sağlığını ve güvenliğini sağlama yükümlülüğünü açıkça belirtir.\n"
        "2. İşverenin Yükümlülükleri\n"
        "İşverenin iş güvenliği kapsamında başlıca yükümlülükleri şunlardır:\n"
        "• Risk değerlendirmesi yapmak,\n"
        "• Çalışanlara iş sağlığı ve güvenliği eğitimi vermek,\n"
        "• Kişisel koruyucu donanım sağlamak,\n"
        "• İş sağlığı ve güvenliği uzmanı ile işyeri hekimi istihdam etmek,\n"
        "• Acil durum planları hazırlamak ve tatbikatları düzenlemek.\n"
        "Bu yükümlülükler, sadece yasal birer zorunluluk değil, aynı zamanda çalışan sağlığını korumanın temel yollarıdır. İşverenler, bu konularda eksiklik gösterirse hem idari yaptırımlarla karşılaşabilir hem de iş kazası durumunda sorumlu tutulabilir.\n"
        "3. Çalışanın Hak ve Sorumlulukları\n"
        "Çalışanlar da iş güvenliği sürecinde etkin rol alır. Başlıca hakları ve sorumlulukları şunlardır:\n"
        "• Sağlıklı ve güvenli ortamda çalışma hakkı,\n"
        "• Riskli durumlarda işi durdurma hakkı,\n"
        "• İSG eğitimi alma hakkı,\n"
        "• Kişisel koruyucu ekipmanları doğru kullanma yükümlülüğü,\n"
        "• Tehlikeli durumları işverene veya İSG birimine bildirme sorumluluğu.\n"
        "Özellikle “çalışmaktan kaçınma hakkı”, hayati tehlike arz eden durumlarda işçinin güvenli alanda bekleme ve durum düzelene kadar çalışmama hakkıdır. Bu hak, yazılı olarak işverene bildirilerek kullanılır ve bu süre zarfında işçiye ücret ödenmeye devam edilir.\n"
        "4. İş Kazası ve Meslek Hastalığı Durumunda Haklar\n"
        "İş kazası veya meslek hastalığı meydana geldiğinde çalışanların çeşitli hakları vardır. Bu haklar şunlardır:\n"
        "• SGK tarafından karşılanan tedavi giderleri,\n"
        "• Geçici iş göremezlik ödeneği,\n"
        "• Maluliyet durumunda sürekli iş göremezlik geliri,\n"
        "• Hayatını kaybeden çalışanların yakınlarına ölüm geliri,\n"
        "• Gerekirse iş mahkemelerinde maddi-manevi tazminat davası açma hakkı.\n"
        "İş kazası bildirimi, işveren tarafından en geç üç iş günü içinde Sosyal Güvenlik Kurumu’na yapılmalıdır. Aksi takdirde idari para cezası uygulanır.\n"
        "5. Denetim ve Yaptırımlar\n"
        "Çalışma ve Sosyal Güvenlik Bakanlığı, işyerlerini denetleyerek iş sağlığı ve güvenliği kurallarına uygunluklarını kontrol eder. Denetimlerde eksiklik tespit edilmesi hâlinde uyarı, faaliyet durdurma ve idari para cezası gibi yaptırımlar uygulanabilir.\n"
        "İşverenin gerekli önlemleri almaması ve bunun sonucunda iş kazası yaşanması hâlinde, ceza hukuku kapsamında da sorumluluğu doğabilir. Özellikle ölümle sonuçlanan kazalarda, taksirle öldürme suçlamasıyla adli süreçler başlatılabilir.\n"
        "6. Çalışanların Başvuru Kanalları\n"
        "Çalışanlar, işyerinde iş sağlığı ve güvenliği ile ilgili bir ihmal veya risk tespit ettiklerinde çeşitli yollarla bu durumu iletebilirler. Bu yollar arasında:\n"
        "• İşyeri İSG kuruluna veya temsilcisine başvurma,\n"
        "• Alo 170 Çalışma ve Sosyal Güvenlik İletişim Merkezi’ni arama,\n"
        "• CİMER üzerinden şikayette bulunma\n"
        "yer almaktadır.\n"
        "7. Sonuç\n"
        "İş güvenliği ve çalışan hakları, sadece bireysel güvenliği değil, kurumsal sürdürülebilirliği de etkileyen kritik bir alandır. Hem işverenin yükümlülükleri hem de çalışanın sorumlulukları net biçimde tanımlanmıştır. Sağlıklı ve güvenli bir çalışma ortamı, iş barışını, verimliliği ve toplum sağlığını doğrudan etkiler. Bu nedenle iş güvenliği, sadece bir yasal zorunluluk değil, aynı zamanda insani bir görevdir.",
    emoji: "🦺",
  ),
  Makale(
    title: "Geçici İş Göremezlik Ödeneği",
    content:
    "1. Tanım ve Yasal Dayanak\n"
        "Geçici iş göremezlik ödeneği, sigortalı bir çalışanın iş kazası, meslek hastalığı, hastalık veya analık gibi nedenlerle çalışamayacak durumda olması halinde, Sosyal Güvenlik Kurumu tarafından geçici süreyle yapılan ödemedir. Bu ödenek, 5510 sayılı Sosyal Sigortalar ve Genel Sağlık Sigortası Kanunu kapsamında sağlanmakta olup, kısa vadeli sigorta kolları arasında yer alır. Uygulama, çalışanın gelir kaybını telafi etmeyi ve tedavi sürecini desteklemeyi amaçlar.\n"
        "2. Yararlanma Koşulları\n"
        "Geçici iş göremezlik ödeneğinden faydalanmak için öncelikle sağlık kuruluşu tarafından düzenlenen istirahat raporunun SGK sistemine girilmiş olması gerekir. Ödeneğin bağlanması için şu şartlar aranır:\n"
        "• İş kazası veya meslek hastalığı durumlarında prim günü şartı yoktur.\n"
        "• Hastalık halinde, iş göremezliğin başladığı tarihten önceki 1 yıl içinde en az 90 gün kısa vadeli sigorta primi bildirilmiş olmalıdır.\n"
        "• Analık halinde, doğum öncesi ve sonrası 8’er haftalık süreler için (çoğul gebelikte doğum öncesi 10 hafta), doğumdan önceki 1 yılda en az 90 gün kısa vadeli prim ödenmiş olması gerekir.\n"
        "Rapor süresince fiilen çalışılmaması, yani işyerinde herhangi bir faaliyette bulunulmaması da zorunludur.\n"
        "3. Süre ve Başlangıç\n"
        "Geçici iş göremezlik ödeneğinin süresi, raporun başlangıç ve bitiş tarihleri arasında yer alan iş göremez günlerine göre belirlenir. Ödeme başlangıcı da rapor türüne göre değişir:\n"
        "• İş kazası ve meslek hastalığı durumlarında, istirahatli olunan ilk günden itibaren ödeme yapılır.\n"
        "• Hastalık durumlarında, üçüncü günden itibaren ödenek verilir; ilk iki gün için ödeme yapılmaz.\n"
        "• Analık halinde, doğumdan önce ve sonra belirlenen toplam 16 haftalık sürede (çoğul gebelikte 18 hafta) çalışılmayan günler için ödeme yapılır.\n"
        "4. Hesaplama Yöntemi\n"
        "Geçici iş göremezlik ödeneği, sigortalının günlük brüt kazancı esas alınarak hesaplanır:\n"
        "• Ayakta tedavi gören sigortalıya günlük kazancının 3’te 2’si,\n"
        "• Yatarak tedavi gören sigortalıya ise günlük kazancının yarısı oranında ödeme yapılır.\n"
        "Günlük kazanç, iş göremezlik öncesindeki son 12 aydaki prime esas kazançların, prim ödeme gün sayısına bölünmesiyle bulunur. Prim günü eksik olanlar için, günlük kazanç belirli bir tavanı geçemez.\n"
        "5. Başvuru ve Ödeme Süreci\n"
        "Ödenek başvurusu için ayrıca bir işlem yapılmaz; raporun elektronik ortamda SGK’ya ulaşmasıyla süreç başlar. İşverenin, çalışanın raporlu olduğu sürede çalışmadığını sisteme bildirmesi gerekir. SGK, gerekli incelemeleri yaptıktan sonra ödeneği e-Devlet üzerinden takip edilebilecek şekilde, kişinin banka hesabına veya PTT’ye gönderir.\n"
        "6. Özel Durumlar\n"
        "• İsteğe bağlı sigortalılar, kısa vadeli prim ödemedikleri için bu ödenekten faydalanamazlar.\n"
        "• Emekli çalışanlar (SGDP’liler) sadece iş kazası ve meslek hastalığı durumunda ödenek alabilir.\n"
        "• 4/b (Bağ-Kur) sigortalıları, bazı durumlarda, örneğin iş kazası veya doğum hallerinde, belirli şartlar sağlandığında ödenek hakkı kazanabilir.\n"
        "7. Sonuç\n"
        "Geçici iş göremezlik ödeneği, sigortalıların sağlık sorunları nedeniyle çalışamadıkları dönemde temel gelirlerini korumalarını sağlayan önemli bir güvencedir. 2025 yılı itibarıyla uygulama detayları güncellenmiş olup, çalışanların bu haktan yararlanabilmesi için mevzuata uygun şartları sağlaması ve rapor süreçlerini dikkatle takip etmesi gerekmektedir.",
    emoji: "🏥",
  ),
  Makale(
    title: "Mobbing ve Çalışan Hakları",
    content:
    "1. Tanım ve Hukuki Dayanak\n"
        "Mobbing, işyerinde bir çalışanın sistematik biçimde yıldırılması, dışlanması, küçümsenmesi veya psikolojik baskıya maruz bırakılması şeklinde tanımlanır. Bu durum, çalışanların hem ruhsal hem de fiziksel sağlığını olumsuz etkileyebilir. Türkiye’de mobbing doğrudan tanımlanmasa da çeşitli kanunlar çerçevesinde korunmaktadır. 4857 sayılı İş Kanunu, 6098 sayılı Türk Borçlar Kanunu ve 5237 sayılı Türk Ceza Kanunu’nda yer alan hükümler mobbinge karşı koruma sağlar. Ayrıca 2025 yılında yayımlanan 2025/3 sayılı Cumhurbaşkanlığı Genelgesi, işyerlerinde psikolojik tacizin önlenmesine yönelik çerçeveyi güncellemiştir.\n"
        "2. Mobbing Davranışları\n"
        "Mobbing, tekil bir davranıştan çok, süreklilik gösteren ve sistemli hale gelen eylemlerle tanımlanır. Bu kapsamda:\n"
        "• Çalışanın bilgi ve tecrübesinin yok sayılması,\n"
        "• Sürekli eleştiriye maruz bırakılması,\n"
        "• Sosyal izolasyona uğratılması,\n"
        "• Yapabileceğinden fazla iş verilerek zorlanması,\n"
        "• Yetkinliğinin altında görevlerle etkisizleştirilmesi,\n"
        "• Hakaret, alay ya da aşağılayıcı davranışlarla itibarsızlaştırılması gibi eylemler mobbing kapsamına girebilir.\n"
        "3. Yasal Haklar ve Fesih Hakkı\n"
        "Mobbinge uğrayan çalışan, İş Kanunu’nun 24. maddesi kapsamında iş sözleşmesini haklı nedenle feshedebilir. Bu durumda çalışana kıdem tazminatı ödenir. Borçlar Kanunu’na göre kişilik hakları zedelenen çalışan, manevi tazminat davası açabilir. Ayrıca Ceza Kanunu çerçevesinde hakaret, tehdit ya da kişiyi hürriyetinden yoksun bırakma gibi suç unsurları oluştuğunda adli süreç başlatılabilir.\n"
        "4. 2025/3 Sayılı Cumhurbaşkanlığı Genelgesi\n"
        "6 Mart 2025 tarihinde yürürlüğe giren bu genelge, kamu kurum ve kuruluşlarında psikolojik tacizle mücadeleyi güçlendirmeyi hedeflemiştir. Genelgede öne çıkan uygulamalar şunlardır:\n"
        "• İşverenlerin ve yöneticilerin önleyici sorumluluklarının vurgulanması,\n"
        "• Kurum içi farkındalık ve bilgilendirme çalışmalarının artırılması,\n"
        "• Şikayetlerin etkin ve gizli biçimde değerlendirileceği mekanizmaların oluşturulması,\n"
        "• Psikolojik Tacizle Mücadele Kurulu’nun yeniden yapılandırılması,\n"
        "• Kurumsal rehberlik hizmetlerinin geliştirilmesi.\n"
        "Bu genelge, özellikle kamu çalışanlarının maruz kaldığı psikolojik taciz vakalarında başvuru ve denetim süreçlerini daha şeffaf ve sistematik hale getirmeyi amaçlamaktadır.\n"
        "5. Başvuru ve Destek Mekanizmaları\n"
        "Mobbinge maruz kalan çalışanlar, durumlarını çeşitli kanallar aracılığıyla ilgili makamlara iletebilir:\n"
        "• İşyerindeki insan kaynakları birimi veya disiplin kurulları,\n"
        "• Çalışma ve Sosyal Güvenlik Bakanlığı,\n"
        "• Alo 170 İletişim Hattı,\n"
        "• Cumhurbaşkanlığı İletişim Merkezi (CİMER),\n"
        "• Türkiye İnsan Hakları ve Eşitlik Kurumu (TİHEK),\n"
        "• Kamu Denetçiliği Kurumu.\n"
        "Şikayet süreci başlatılırken yazılı ve belgeli kayıtlar (e-posta, tanık ifadeleri, mesajlar) sürecin sağlıklı ilerlemesi açısından önem taşır.\n"
        "6. Kurumsal Önlemler\n"
        "İşverenler, psikolojik tacizi önlemekle yükümlüdür. Bu kapsamda:\n"
        "• İş yerinde etik davranış kurallarının yazılı hale getirilmesi,\n"
        "• Çalışanlara yönelik düzenli eğitimler düzenlenmesi,\n"
        "• Şikayetlerin bağımsız bir kurul tarafından değerlendirilmesi,\n"
        "• Psikolojik destek hizmetlerine erişim sağlanması gibi önlemler alınabilir.\n"
        "Bu uygulamalar hem iş barışını sağlar hem de işverenin hukuki sorumluluğunu azaltır.\n"
        "7. Sonuç\n"
        "Mobbing, işyeri ortamında ciddi sosyal, psikolojik ve hukuki sonuçlara yol açabilir. 2025 yılı itibarıyla yürürlüğe giren düzenlemeler ve genelgeler, bu konuda daha güçlü bir yasal zeminin oluşmasına katkı sağlamıştır. Çalışanlar, haklarını bilmeli; işverenler ise önleyici ve destekleyici kurumsal uygulamaları hayata geçirmelidir. Sağlıklı ve güvenli bir çalışma hayatı için mobbing ile mücadele, bireysel olduğu kadar kurumsal bir sorumluluktur.",
    emoji: "🛡️",
  ),
  Makale(
    title: "İhbar Tazminatı Uygulaması",
    content:
    "1. Yasal Dayanak ve Tanım\n"
        "İhbar tazminatı, 4857 sayılı İş Kanunu’nun 17. maddesi uyarınca düzenlenen ve işverenin iş sözleşmesini sona erdirirken riayet etmesi gereken yasal bir yükümlülüktür. Belirsiz süreli iş sözleşmelerinin feshinde taraflardan biri, sözleşmeyi sona erdirmeden önce diğer tarafa bildirimde bulunmalı; aksi hâlde ihbar tazminatı ödenmelidir.\n"
        "2. İhbar Süreleri\n"
        "İhbar süresi, işçinin işyerindeki kıdemine göre belirlenir:\n"
        "• 6 aydan az çalışmış işçiler için: 2 hafta\n"
        "• 6 ay ile 1.5 yıl arası çalışmış işçiler için: 4 hafta\n"
        "• 1.5 yıl ile 3 yıl arası çalışmış işçiler için: 6 hafta\n"
        "• 3 yıldan fazla çalışmış işçiler için: 8 hafta\n"
        "Bu süreler, hem işçi hem işveren için geçerli olup, karşılıklı yükümlülük doğurur.\n"
        "3. Hak Kazanma Şartları\n"
        "İhbar tazminatına hak kazanılabilmesi için şu şartların sağlanması gerekir:\n"
        "• İş sözleşmesinin belirsiz süreli olması,\n"
        "• Sözleşmenin feshi sırasında ihbar süresine uyulmaması,\n"
        "• Fesih işleminin haklı bir nedene dayanmaması.\n"
        "4. Tazminatın Hesaplanması\n"
        "İhbar tazminatı, işçinin brüt ücretine ve ilgili ihbar süresine göre hesaplanır. Aylık brüt ücret 30’a bölünerek günlük ücret bulunur, ardından bu tutar çalışanın kıdemine karşılık gelen gün sayısı ile çarpılır. Tazminattan damga vergisi ve gelir vergisi kesintisi yapılır. Damga vergisi oranı, brüt tazminat tutarının binde 7,59’u kadardır.\n"
        "İhbar tazminatına ilişkin tahmini hesaplamalar, Sosyal Güvenlik Mobil uygulamamız üzerinden kolaylıkla yapılabilmektedir.\n"
        "5. Ödeme Zamanı\n"
        "İşveren, ihbar süresine uymaksızın sözleşmeyi feshediyorsa, tazminat tutarını iş sözleşmesinin sona erdiği tarihte ödemek zorundadır. Ödemenin gecikmesi durumunda, yasal faiz uygulanabilir.\n"
        "6. Tazminatın Ödenmediği Durumlar\n"
        "Aşağıdaki durumlarda ihbar tazminatı ödenmez:\n"
        "• İşverenin işçiyi haklı nedenle işten çıkarması,\n"
        "• İşçinin haklı nedenle işten ayrılması,\n"
        "• Belirli süreli iş sözleşmelerinin sona ermesi,\n"
        "• Deneme süresi içinde sözleşmenin sona erdirilmesi.\n"
        "7. Zamanaşımı Süresi\n"
        "İhbar tazminatı alacakları için zamanaşımı süresi, iş sözleşmesinin sona erdiği tarihten itibaren beş yıldır. Bu sürenin sonunda ihbar tazminatı için dava açma hakkı sona erer.\n"
        "8. Sonuç\n"
        "İhbar tazminatı, iş ilişkilerinin düzenli ve hukuka uygun şekilde sona erdirilmesi açısından önemlidir. İşverenin, sözleşme fesihlerinde ihbar süresine uyması ya da tazminat ödemesi, hem yasal yükümlülüklerin yerine getirilmesini sağlar hem de çalışanlar açısından mağduriyetin önüne geçer. Bu nedenle işverenlerin ihbar tazminatı konusundaki yükümlülüklerini dikkatle yerine getirmeleri gerekmektedir.",
    emoji: "📅",
  ),
  Makale(
    title: "Asgari Ücret ve Sosyal Haklar",
    content:
    "1. Tanım ve Hukuki Dayanak\n"
        "Asgari ücret, bir işçiye yasalarca belirlenen en düşük aylık veya günlük çalışma ücreti olup, temel geçim düzeyini karşılamayı hedefler. Türkiye’de asgari ücret, 4857 sayılı İş Kanunu ve 2004 yılında yürürlüğe giren Asgari Ücret Yönetmeliği çerçevesinde düzenlenmektedir. Ücreti belirleme yetkisi Asgari Ücret Tespit Komisyonu’na aittir. Bu komisyon, işçi, işveren ve devlet temsilcilerinden oluşur ve yılda en az bir kez toplanarak yeni tutarı belirler.\n"
        "2. Asgari Ücretin Bileşenleri ve Uygulama Şekli\n"
        "Asgari ücret brüt ve net olarak belirlenir. Brüt tutar; gelir vergisi, damga vergisi ve sigorta prim kesintileri yapılmadan önceki miktarı ifade eder. Net tutar ise bu kesintiler yapıldıktan sonra çalışanın eline geçen gerçek maaştır. 2025 yılı itibarıyla net asgari ücret 22.104,67 TL, brüt asgari ücret ise 26.005,50 TL olarak belirlenmiştir. Günlük brüt asgari ücret 866,85 TL, günlük net asgari ücret ise 736,82 TL’dir.\n"
        "Asgari ücret; yaş, cinsiyet veya sektör farkı gözetilmeksizin tüm çalışanlara eşit olarak uygulanır. Ancak 18 yaşından küçük işçilere, çıraklara ve stajyerlere özel durumlar geçerlidir. Bu ücretin altında ödeme yapılması hukuken yasaktır.\n"
        "3. Asgari Ücretle Birlikte Sağlanan Sosyal Haklar\n"
        "Asgari ücretle çalışan işçiler yalnızca maaş almakla kalmaz; aynı zamanda birtakım sosyal ve yasal haklara da sahiptirler. Bu haklar, hem iş güvencesini hem de yaşam standartlarını destekleyici niteliktedir:\n"
        "• Sigortalı Çalışma Hakkı: İşveren, asgari ücretle çalışan işçiyi Sosyal Güvenlik Kurumu’na bildirmekle yükümlüdür. Bu sigorta, sağlık hizmetlerinden yararlanmayı ve emeklilik birikimini kapsar.\n"
        "• Yıllık Ücretli İzin: Asgari ücretli çalışanlar da diğer çalışanlar gibi kıdeme göre yıllık izin hakkına sahiptir.\n"
        "• Fazla Mesai Ücreti: Haftalık 45 saati aşan çalışmalar için fazla mesai ödenmesi zorunludur.\n"
        "• Hafta Tatili Ücreti: Pazar günü ya da haftalık izin gününde çalışılması hâlinde ek ücret ödenmelidir.\n"
        "• Ulusal Bayram ve Genel Tatil Ücretleri: Resmi tatil günlerinde çalışılması durumunda, işçiye en az bir günlük ek ücret ödenir.\n"
        "• Doğum ve Analık Hakları: Kadın çalışanlar doğum öncesi ve sonrası analık izni ile geçici iş göremezlik ödeneği alma hakkına sahiptir.\n"
        "• İşsizlik Sigortası: Asgari ücretli işçi belirli prim koşullarını sağladığında işsiz kalması hâlinde işsizlik maaşı alabilir.\n"
        "4. Asgari Ücretin Günlük Hayata Etkisi\n"
        "Asgari ücret; yalnızca bir ücret politikası değil, aynı zamanda ekonomik ve sosyal politika aracıdır. Bu ücret, ülke genelindeki geçim standartlarını doğrudan etkiler. Barınma, beslenme, eğitim ve ulaşım gibi temel ihtiyaçların karşılanabilmesi için asgari ücretin yeterli düzeyde olması büyük önem taşır.\n"
        "Asgari ücretin artışı, sosyal yardımlar, maaş dengeleri ve işveren maliyetleri üzerinde doğrudan etkili olur. Bu nedenle belirleme süreci yalnızca ekonomik değil, sosyal boyutları da dikkate alınarak yürütülür.\n"
        "5. 2025 Yılı Asgari Ücret Verileri\n"
        "2025 yılı itibarıyla asgari ücretle ilgili güncel veriler aşağıdaki gibidir:\n"
        "• Aylık Brüt Asgari Ücret: 26.005,50 TL\n"
        "• Aylık Net Asgari Ücret: 22.104,67 TL\n"
        "• Günlük Brüt Asgari Ücret: 866,85 TL\n"
        "• Günlük Net Asgari Ücret: 736,82 TL\n"
        "• SGK Primi (İşçi Payı %14): 3.640,77 TL\n"
        "• İşsizlik Sigortası Primi (İşçi Payı %1): 260,06 TL\n"
        "• Toplam Kesintiler: 3.900,83 TL\n"
        "• İşverene Toplam Maliyet: 30.621,48 TL (SGK işveren primi ve işsizlik sigortası primi dahil)\n"
        "6. Sonuç\n"
        "Asgari ücret, çalışanların temel ihtiyaçlarını karşılamayı amaçlayan anayasal bir haktır. Bu ücretin altında çalıştırılmak yasak olduğu gibi, asgari ücretle çalışanların sosyal güvencelerinin sağlanması da zorunludur. Asgari ücret yalnızca bir sayı değil, emeğin asgari değerinin göstergesidir. İşveren ve çalışanların, bu hakkın uygulanması konusunda bilinçli ve sorumlu davranmaları, toplumsal refahın artırılması açısından büyük önem taşır.",
    emoji: "💰",
  ),
  Makale(
    title: "Analık Sigortası ve Haklar",
    content:
    "1. Tanım ve Yasal Dayanak\n"
        "Analık sigortası, kadın çalışanların gebelik ve doğum dönemlerinde maddi ve sosyal güvence sağlayan bir sosyal sigorta türüdür. 5510 sayılı Sosyal Sigortalar ve Genel Sağlık Sigortası Kanunu’na göre; hizmet akdine tabi çalışan kadınlar, kendi nam ve hesabına çalışanlar ve sigortalı erkeğin sigortalı olmayan eşi analık sigortasından yararlanabilir. Analık hali; gebeliğin başladığı tarihten itibaren doğum sonrası ilk 8 hafta (çoğul gebelikte 10 hafta) süreyi kapsar. Bu kapsam, annenin hem kendisinin hem de bebeğinin sağlığını güvence altına almak için düzenlenmiştir.\n"
        "2. Analık Hali ve Geçici İş Göremezlik Ödeneği\n"
        "Hizmet akdine tabi ya da kendi nam ve hesabına çalışan kadınlar, analık hali nedeniyle geçici iş göremezlik ödeneği alma hakkına sahiptir. Bu ödenekten faydalanmak için doğumdan önceki 1 yıl içinde en az 90 gün kısa vadeli sigorta primi ödenmiş olmalıdır.\n"
        "Analığa bağlı geçici iş göremezlik ödeneği tutarı; annenin sigortalılık durumu, brüt kazancı ve tedavi şekline göre değişiklik gösterebilir. Bu hesaplama işlemi, Sosyal Güvenlik Mobil uygulamamız üzerinden hızlı ve güvenilir şekilde yapılabilir. Uygulamamız, güncel mevzuata göre işlem yaparak annenin hak ettiği ödenek tutarını otomatik olarak hesaplar.\n"
        "3. Emzirme Ödeneği\n"
        "Emzirme ödeneği; doğum yapan sigortalı kadına veya sigortalı erkeğin doğum yapan sigortalı olmayan eşine verilir. Hizmet akdine tabi çalışanlar, kendi nam ve hesabına çalışanlar ile gelir/aylık alan sigortalılar bu haktan yararlanabilir.\n"
        "Şart olarak, doğumdan önceki 1 yıl içinde en az 120 gün kısa vadeli sigorta primi ödenmiş olması gerekmektedir. 2025 yılı itibarıyla emzirme ödeneği tutarı 1.238 TL’dir. Bu ödenek tek seferlik olup, başvuru sonrası sigortalının hesabına veya PTT aracılığıyla adına yatırılır. Emzirme ödeneği, annenin doğum sonrası dönemdeki ihtiyaçlarını karşılaması açısından küçük fakat önemli bir destek sunar.\n"
        "4. Başvuru Süreci\n"
        "Geçici iş göremezlik ödeneği başvurusu doğum sonrası işveren tarafından e-SGK sistemi üzerinden veya SGK il müdürlüklerine şahsen yapılabilir. İşveren, doğumdan sonra en geç 5 iş günü içinde Geçici İş Göremezlik Ödeneği Talep Formu, doğum raporu, doğum belgesi ve kimlik fotokopisi ile SGK’ya başvurmalıdır.\n"
        "Ödeme, SGK sisteminde kayıtlı IBAN’a yatırılır; IBAN yoksa PTT aracılığıyla ödeme yapılır. Başvuru ve ödeme süreci e-Devlet üzerinden takip edilebilir. Eksik belge varsa, sigortalı doğrudan SGK’ya başvurabilir. Süreçte herhangi bir aksaklık yaşanmaması için belgelerin eksiksiz ve doğru bir şekilde hazırlanması gerekmektedir.\n"
        "5. Doğum Sonrası Ek Haklar\n"
        "Doğum yapan çalışanlara:\n"
        "• 6 aya kadar ücretsiz izin hakkı\n"
        "• 1 yaşına kadar günlük 1,5 saat süt izni (çoğul gebelikte 2 hafta doğum öncesi izne eklenir)\n"
        "• Analık izni sonrası 30 gün boyunca yarım gün çalışma hakkı\n"
        "verilmektedir.\n"
        "Bu haklar, çalışan annenin iş ve aile hayatı arasında denge kurmasını kolaylaştırır. Süt izni hakkı, annenin bebeğin beslenme ihtiyaçlarını karşılamasına olanak tanırken, yarım gün çalışma hakkı annelere iş yaşamına daha yumuşak bir geçiş yapma şansı verir. Ayrıca bu düzenlemeler, işverenin çalışan anneye karşı sorumluluklarını da netleştirir.\n"
        "6. Yasal Korumalar\n"
        "4857 sayılı İş Kanunu’nun 18. maddesi uyarınca, analık izni süresince işveren tarafından işçinin iş akdi feshedilemez. Bu sürede işten çıkarılan kadın çalışan:\n"
        "• Kıdem ve ihbar tazminatına hak kazanır\n"
        "• İşe iade davası açabilir\n"
        "Davanın kazanılması durumunda, işveren çalışana işe iade hakkı tanımazsa 4 ila 8 aylık brüt ücreti kadar işe başlatmama tazminatı ödemekle yükümlüdür. Bu koruma mekanizması, annelerin iş güvencesini doğum öncesi ve sonrası süreçte etkin biçimde sağlar.\n"
        "7. Hak İhlallerinde Başvuru Yolları\n"
        "Çalışanlar, analık haklarına ilişkin ihlalleri Çalışma ve Sosyal Güvenlik Bakanlığı’na bildirebilir ya da ALO 170 hattı üzerinden şikâyet oluşturabilir. Ayrıca SGK’nın internet sitesi ve e-Devlet uygulaması üzerinden yapılan başvurular da sonuç alma sürecini hızlandırmaktadır. Bu mekanizmalar, çalışan annelerin haklarının korunmasını ve güvence altına alınmasını sağlar.\n"
        "8. Sonuç\n"
        "Analık sigortası, kadın çalışanların gebelik ve doğum sürecini güvence altına alan önemli bir sosyal haktır. Geçici iş göremezlik ödeneği, emzirme yardımı ve doğum sonrası sağlanan izin ve korumalar, iş hayatında kadının yerini güçlendirir. Bu hakların etkin kullanımı, annelerin hem ekonomik hem de sosyal açıdan desteklenmesini sağlar. Aynı zamanda bu uygulamalar, toplumun genel refah düzeyini ve kadın istihdamını artırma yönünde de katkı sunar.",
    emoji: "📝",
  ),
  Makale(
    title: "Fazla Mesai Ücreti",
    content:
    "1. Yasal Dayanak ve Tanım\n"
        "Fazla mesai, 4857 sayılı İş Kanunu’nun 41. maddesi uyarınca, haftalık 45 saati aşan çalışmalar olarak tanımlanır. Bu süreyi aşan her çalışma, fazla çalışma (fazla mesai) olarak kabul edilir ve işçiye ek ücret ödenmesini gerektirir. İşçinin fazla mesai yapabilmesi için yazılı onayı alınmalıdır.\n"
        "2. Fazla Mesai ve Fazla Sürelerle Çalışma Ayrımı\n"
        "Eğer iş sözleşmesinde haftalık çalışma süresi 45 saatin altında belirlenmişse (örneğin 40 saat), 45 saate kadar yapılan ek çalışmalar “fazla sürelerle çalışma” olarak adlandırılır. Bu tür çalışmalar için işçiye, normal saatlik ücretinin %25 fazlası ödenir. 45 saati aşan çalışmalar ise “fazla mesai” olarak kabul edilir ve %50 zamlı ücretle ödenir.\n"
        "3. Fazla Mesai Ücreti Nasıl Hesaplanır?\n"
        "Fazla mesai ücreti hesaplanırken, işçinin saatlik brüt ücreti esas alınır. Bu ücret, aylık brüt maaşın, aylık çalışma saatine (genellikle 225 saat) bölünmesiyle bulunur. Elde edilen saatlik ücret, fazla mesai saatleriyle çarpılarak toplam fazla mesai ücreti hesaplanır.\n"
        "4. Fazla Mesai Sınırları ve İstisnalar\n"
        "İş Kanunu’na göre, bir işçi yılda en fazla 270 saat fazla mesai yapabilir. Ayrıca, günlük çalışma süresi 11 saati aşamaz. Bu sınırlar, işçinin sağlığını korumak amacıyla getirilmiştir. Aşağıdaki durumlarda fazla mesai yaptırılamaz:\n"
        "• 18 yaşını doldurmamış işçiler\n"
        "• Hamile, yeni doğum yapmış ve çocuk emziren işçiler\n"
        "• Kısmi süreli çalışanlar\n"
        "• Sağlık durumu fazla mesaiye uygun olmayan işçiler\n"
        "• Yer altı maden işlerinde çalışanlar\n"
        "5. Serbest Zaman Kullanımı\n"
        "İşçi, fazla mesai ücreti almak yerine, fazla çalıştığı her saat için 1 saat 30 dakika serbest zaman kullanabilir. Bu serbest zaman, işçinin talebi üzerine ve 6 ay içinde, ücretinde bir kesinti olmadan kullandırılmalıdır. İşveren, işçiyi serbest zaman kullanmaya zorlayamaz.\n"
        "6. Fazla Mesai Ücretinin Ödenmemesi Durumunda İşçinin Hakları\n"
        "İşverenin, işçinin yaptığı fazla mesai karşılığında ücret ödememesi, işçiye iş sözleşmesini haklı nedenle feshetme hakkı verir. Bu durumda işçi, kıdem tazminatı ve diğer yasal haklarını talep edebilir.\n"
        "7. Fazla Mesai Ücretinde Zamanaşımı\n"
        "Fazla mesai alacakları için zamanaşımı süresi 5 yıldır. İşçi, geriye dönük 5 yıl içinde yaptığı fazla mesai ücretlerini talep edebilir. Bu sürenin aşılması durumunda, işveren zamanaşımı savunması yapabilir ve alacak talebi reddedilebilir.\n"
        "8. Çalışanın Hakları Açısından Fazla Mesai\n"
        "Fazla mesai hakkı, işçinin fazla çalışmasının karşılığını adil biçimde almasını güvence altına alan temel bir çalışma hakkıdır. İşçi, fazla mesaiye rızası olmadan zorlanamaz ve fazla mesai yaptığı takdirde zamlı ücret ya da serbest zaman talep etme hakkına sahiptir. Çalışanlar, fazla mesai sürelerini, ücretlerini ve onay süreçlerini takip etmeli; gerektiğinde kayıt tutmalı ve haklarını korumak adına yasal yollara başvurmaktan çekinmemelidir. Fazla mesai, bir ayrıcalık değil, ancak karşılığı ödendiği sürece yasal bir zorunluluk olabilir.\n"
        "9. Sonuç\n"
        "Fazla mesai, işçinin ek çalışmaları karşılığında hak ettiği bir ücrettir ve yasal düzenlemelerle korunmaktadır. İşverenler, fazla mesai yaptırmadan önce işçinin onayını almalı ve yasal sınırlar içinde kalmalıdır. İşçiler ise haklarını bilerek, fazla mesai ücretlerini zamanında talep etmelidir. Her iki tarafın da yasal yükümlülüklerini yerine getirmesi, iş barışının sağlanması açısından önemlidir.",
    emoji: "⏰",
  ),
  Makale(
    title: "Sürekli İş Göremezlik Geliri",
    content:
    "1. Tanım ve Yasal Dayanak\n"
        "Sürekli iş göremezlik geliri, iş kazası veya meslek hastalığı nedeniyle meslekte kazanma gücünü en az %10 oranında kaybeden sigortalılara bağlanan sürekli ve düzenli ödemedir. 5510 sayılı Sosyal Sigortalar ve Genel Sağlık Sigortası Kanunu’nun 19. ve 20. maddeleri kapsamında düzenlenmiştir. Bu gelir, çalışanın kalıcı gelir kaybını telafi etmek amacıyla sağlanır ve yaşamını sürdürebilmesine destek olur.\n"
        "2. Gelir Bağlanma Koşulları\n"
        "Sürekli iş göremezlik geliri bağlanabilmesi için şu şartların sağlanması gerekir:\n"
        "• İş kazası ya da meslek hastalığı sonucu kalıcı bir iş göremezlik durumu meydana gelmiş olmalıdır.\n"
        "• SGK tarafından yetkilendirilen sağlık kuruluşlarından alınan sağlık kurulu raporuna göre, meslekte kazanma gücü en az %10 oranında azalmış olmalıdır.\n"
        "• Sigortalılık durumu ve kazanın meslekle ilişkisi tespit edilmiş olmalıdır.\n"
        "Geçici iş göremezlik ödeneği süreci tamamlandıktan sonra, kalıcı durumun tespiti için sağlık raporu düzenlenir ve SGK tarafından sürekli gelir bağlanmasına karar verilir.\n"
        "3. Gelir Türleri\n"
        "Sürekli iş göremezlik geliri, iki başlık altında değerlendirilir:\n"
        "• Tam Sürekli İş Göremezlik: Meslekte kazanma gücünün %100 kaybı hâlinde verilir. Bu durumda sigortalıya, prime esas günlük kazancının %70’i oranında gelir bağlanır.\n"
        "• Kısmi Sürekli İş Göremezlik: Meslekte kazanma gücü %10 ila %99 arasında kaybedilmişse, tam gelir oranı üzerinden iş göremezlik derecesine göre orantılı bir gelir bağlanır.\n"
        "Gelir bağlama oranı hesaplanırken, çalışanın prime esas kazancı, iş göremezlik derecesi ve varsa bakmakla yükümlü kişilerin durumu dikkate alınır.\n"
        "4. Hak Sahipleri ve Ölüm Hali\n"
        "Sürekli iş göremezlik geliri almakta olan sigortalı vefat ettiğinde, ölüm geliri bağlanması mümkündür. Bu durumda, gelirden eşi, çocukları veya hak sahibi diğer yakınları faydalanabilir. Ayrıca hak sahibi çocukların öğrenim durumuna göre gelir alma süresi uzayabilir.\n"
        "Vefat durumu, iş kazası veya meslek hastalığı nedeniyle gerçekleşmişse, hak sahiplerine cenaze ödeneği ve gelir bağlanması hakkı da doğabilir.\n"
        "5. Başvuru Süreci\n"
        "Sürekli iş göremezlik geliri için başvuru işlemleri şu adımları içerir:\n"
        "• Sigortalı, iş kazası veya meslek hastalığı nedeniyle tedavi süreci sonunda sağlık kurulu raporu alır.\n"
        "• Bu rapor SGK tarafından incelenir ve değerlendirme yapılır.\n"
        "• İş göremezlik derecesi %10 ve üzerindeyse, gerekli belgeler tamamlandıktan sonra gelir bağlama işlemi başlatılır.\n"
        "• Gelir, SGK tarafından belirlenen tarihlerde sigortalının banka hesabına veya PTT aracılığıyla ödenir.\n"
        "Başvuru süreci e-Devlet veya SGK il müdürlükleri aracılığıyla takip edilebilir.\n"
        "6. Güncelleme ve Kontrol\n"
        "Kısmi sürekli iş göremezlik gelirine hak kazananlar, sağlık durumlarındaki değişikliklerin değerlendirilmesi amacıyla SGK tarafından belirli aralıklarla kontrol muayenesine çağrılabilir. Eğer çalışma gücünde artış tespit edilirse, gelir azaltılabilir veya kesilebilir.\n"
        "Ancak %100 oranında tam iş göremezlik tespiti yapılanlar için bu tür periyodik kontroller uygulanmaz; gelir süresiz şekilde devam eder.\n"
        "7. Sonuç\n"
        "Sürekli iş göremezlik geliri, sigortalının kalıcı gelir kaybı yaşadığı durumlarda yaşam standartlarını korumayı hedefleyen bir sosyal güvenlik uygulamasıdır. Özellikle iş kazası ve meslek hastalığı gibi beklenmedik durumlarda, gelir desteği sağlanması çalışanın hem ekonomik hem de psikolojik yükünü azaltır. Bu gelirin alınabilmesi için gerekli sağlık raporlarının titizlikle hazırlanması ve başvuru sürecinin doğru yürütülmesi önem arz eder.",
    emoji: "🏥",
  ),
];