// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDswI1NTZJN2h1aAmTvBItHtKSfpAuY92E',
    appId: '1:100925070763:web:b86311d3afa0d9e5f9c6ee',
    messagingSenderId: '100925070763',
    projectId: 'sosyal-guvenlik-cepte-61d36',
    authDomain: 'sosyal-guvenlik-cepte-61d36.firebaseapp.com',
    storageBucket: 'sosyal-guvenlik-cepte-61d36.firebasestorage.app',
    measurementId: 'G-KYKQSRC817',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC67EHhCM7xb2FfjNZ3r5i_iTIbjXMSgAc',
    appId: '1:100925070763:android:f88d58245d173b2ff9c6ee',
    messagingSenderId: '100925070763',
    projectId: 'sosyal-guvenlik-cepte-61d36',
    storageBucket: 'sosyal-guvenlik-cepte-61d36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXAQ1PQDzI33EzX9wTHcNCtA_eQ6LZGko',
    appId: '1:100925070763:ios:2fe2bcc38bb95ceef9c6ee',
    messagingSenderId: '100925070763',
    projectId: 'sosyal-guvenlik-cepte-61d36',
    storageBucket: 'sosyal-guvenlik-cepte-61d36.firebasestorage.app',
    iosBundleId: 'com.sosyalguvenlik.mobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXAQ1PQDzI33EzX9wTHcNCtA_eQ6LZGko',
    appId: '1:100925070763:ios:6c64eec5bb71f711f9c6ee',
    messagingSenderId: '100925070763',
    projectId: 'sosyal-guvenlik-cepte-61d36',
    storageBucket: 'sosyal-guvenlik-cepte-61d36.firebasestorage.app',
    iosBundleId: 'com.sosyalguvenlik.mobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDswI1NTZJN2h1aAmTvBItHtKSfpAuY92E',
    appId: '1:100925070763:web:207b952d5ef44233f9c6ee',
    messagingSenderId: '100925070763',
    projectId: 'sosyal-guvenlik-cepte-61d36',
    authDomain: 'sosyal-guvenlik-cepte-61d36.firebaseapp.com',
    storageBucket: 'sosyal-guvenlik-cepte-61d36.firebasestorage.app',
    measurementId: 'G-05J0QEDVT0',
  );
}
